# spring.data.mongodb.host=${MONGO_HOST:localhost}
# spring.data.mongodb.port=${MONGO_PORT_27017:27017}

spring.data.mongodb:
  host: localhost
  port: 27017
  
---
spring.config.activate.on-profile: crac

spring:
  cloud:
    refresh:
      never-refreshable:
      extra-refreshable:
      - com.mongodb.client.MongoClient
    #   - com.mongodb.connection.ClusterDescription
    #   - com.mongodb.connection.ServerDescription
  application:
    name: data-mongodb-test
  config:
    import: file:./runtime-configuration.yml